### ISSUE TITLE
Bug report: Significant difference between SimVascular and  Poiseuille's law (single tube flow)

### ISSUE THREAD

**Issue by pvpnarao** [SimVascular/svOneDSolver#112]
### Description

The resistance of a single rigid tube is calculated as (Pin-Pout)/Q . This ratio can also be approximated from Poiseuille's law.
After making the big fix mentioned in this pull request, We tried to run a simple flow through a single tube usind svOneDSolver. The differen in the results is nearly 30%  

### Reproduction

The case details are as follows (all in cgs units)
Tube Length = 50
Tube Radius = 1.2
Linear Material Eh/r = 75000
Downstream Resistance = 51.97148278636055
Fluid Density = 1.0
Fluid Viscosity = 0.05
Steady State Flow = 100

**Entries of the input file as follows**

```
MODEL demo

NODE 0 0.0 0.0 50.0
NODE 1 0.0 0.0 0.0


SEGMENT edge0 0 50.0 500 0 1 4.523893421169302 4.523893421169302 0.0 MAT1 NONE 0.0 0 0 RESISTANCE RESISTANCE_0

DATATABLE RESISTANCE_0 LIST
0.0 51.97148278636055
0.0 0.0
ENDDATATABLE


DATATABLE INFLOW LIST
0.0 0.0
0.20408163265306123 0.41049930883769736
0.40816326530612246 1.6352568480485274
0.6122448979591837 3.6541621326989127
0.8163265306122449 6.434064793830535
1.0204081632653061 9.92931890660217
1.2244897959183674 14.08253249511362
1.4285714285714286 18.82550990706332
1.6326530612244898 24.080371584473752
1.836734693877551 29.760832843880316
2.0408163265306123 35.77362066844838
2.2448979591836733 42.020005248331024
2.4489795918367347 48.39742112141723
2.6530612244897958 54.801151295384074
2.857142857142857 61.12604669781572
3.061224489795918 67.26825272106538
3.2653061224489797 73.12691451204178
3.4693877551020407 78.60583300610847
3.673469387755102 83.61504451306585
3.877551020408163 88.07229791845673
4.081632653061225 91.90440524459203
4.285714285714286 95.04844339512096
4.489795918367347 97.45278735053343
4.6938775510204085 99.07795784955327
4.8979591836734695 99.89726963751681
5.1020408163265305 100
5.3061224489795915 100
5.510204081632653 100
5.714285714285714 100
5.918367346938775 100
6.122448979591836 100
6.326530612244898 100
6.530612244897959 100
6.73469387755102 100
6.938775510204081 100
7.142857142857143 100
7.346938775510204 100
7.551020408163265 100
7.755102040816326 100
7.959183673469388 100
8.16326530612245 100
8.36734693877551 100
8.571428571428571 100
8.775510204081632 100
8.979591836734693 100
9.183673469387756 100
9.387755102040817 100
9.591836734693878 100
9.795918367346939 100
10.0 100
ENDDATATABLE

SOLVEROPTIONS 0.01 1 1000 4 INFLOW FLOW 1.0e-6 1 1

MATERIAL MAT1 LINEAR 1.0 0.05 0.0 1.0 75000.0 0.0 0.0

OUTPUT TEXT
```

### Expected behavior

A difference of 30 % is observed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by pvpnarao** [comment]
Solutions values obtained from svOneDsolver

![Solutions](https://github.com/SimVascular/svOneDSolver/assets/23018249/2fb8f3ad-bcbd-4d9f-a4c8-d271d809f168)

**Comment by mrp089** [comment]
This is an easy fix! Have a look at the ROM simulation guide: https://simvascular.github.io/documentation/rom_simulation.html The "material exponent" determines the polynomial degree of the velocity profile. For a Poiseuille  solution you'd have a quadratic profile and this a material exponent of two. Changing that in your input file should yield the desired result. You can also have a look at our test cases, some of which also reproduce Poiseuille solutions.
