### ISSUE TITLE
Compile in Windows 10

### ISSUE THREAD

**Issue by simmed00** [SimVascular/svOneDSolver#48]
I tried to compile under win10-64bit. I used Cmake-GUI to configure the path of swig, python, boost, but I did not find an option of MPI.
I then generated the visual studio 2017 solution, and tried to compile it in vs2017.
It gave me a lot of errors:
Most of them are 'M_PI' undeclared identifier in cvOneDBFSolver.cxx in OneDSolver project. I declared a double M_PI myself, this seems to solve the problem.
But then I still have the LNK2001 and LNK1120 unresolved externals. 
Has anyone successfully compiled it under Windows 10?

**Comment by osmsc** [comment]
Hi Simmed00,

The CMake build is not the best way to build on Windows.  Please try compiling using the "Make" build on Windows.  The instructions are contained in the:

"svSolver/BuildWithMake" directory.

Have you tried the compiled version of svSolver on your system?  We provide an executable for Windows 10 64  bit on simtk.org.

Nathan
SimVascular Support Team

**Comment by simmed00** [comment]
Thank you very much for the help.

I somehow figured out how to compile in Win10 using cmake and VS2017.

Having a compiled exe is much more convenient!
________________________________
发件人: Nathan Wilson <notifications@github.com>
发送时间: 2020年4月28日 0:59
收件人: SimVascular/svOneDSolver <svOneDSolver@noreply.github.com>
抄送: Chubin OU <cou@connect.ust.hk>; Author <author@noreply.github.com>
主题: Re: [SimVascular/svOneDSolver] Compile in Windows 10 (#48)


Hi Simmed00,

The CMake build is not the best way to build on Windows. Please try compiling using the "Make" build on Windows. The instructions are contained in the:

"svSolver/BuildWithMake" directory.

Have you tried the compiled version of svSolver on your system? We provide an executable for Windows 10 64 bit on simtk.org.

Nathan
SimVascular Support Team

―
