### ISSUE TITLE
Pressure boundary condition not working

### ISSUE THREAD

**Issue by mrp089** [SimVascular/svOneDSolver#50]
The PRESSURE boundary condition doesn't work anymore. Test case `04_simpleArtery_Pressure.in` crashes with `ERROR: pressure information is not prescribed`.

The error was caused by adding the following two lines in `cvOneDMthModelBase.cxx` in commit 6d67d26:

https://github.com/SimVascular/svOneDSolver/blob/017b42e578c813935bab0db1410eb2159865de7b/Code/Source/cvOneDMthModelBase.cxx#L163-L164

@jseo0 Can you please have a look at this?

**Comment by vvedula22** [comment]
I had the same error even with 01_simpleArtery_Flow.in. I reported errors while compiling from source using both SuperLU and CSparse. With SuperLU, I had difficulty with some header files and for CSparse, I had trouble when including python.

**Comment by mrp089** [comment]
@vvedula22 We fixed bugs in the code in 50edf9c. The test case you mention will probably be removed as the FLOW boundary condition is currently not supported. If you need that BC, please let us know.
