### ISSUE TITLE
Code cleanup may cause incorrect pressure drops

### ISSUE THREAD

**Issue by wgyang** [SimVascular/svOneDSolver#54]
#49 reported that the pressure drop is incorrect for a cylinder with steady inflow. My code produced the target pressure drop after the material option was corrected. However, @mrp089 reported that the same input file produced no pressure drop.  
After checking out earlier versions, these two modifications produced incorrect pressure drop: 
commit 93f0fb468a096db6a013cb597438ae9619a5ac61
4/29/2019
commit d85751e94cd0cfb3aa52218e747561f9d28d668a
5/22/2019

These modifications can produce correct pressures on my laptop.
commit b689f8c79402ad9195246a2a4d24326d6249f221
4/29/2019
commit 97edcc128112f3d60f358b132b9006f150f85d7a
5/13/2019
commit 9837884cb92b53aa3e06efdffa1f8a3719bb0d3a
5/13/2019

It seems the code cleanup for unused subroutines caused this issue.

**Comment by caseyfleeter** [comment]
@mrp089 this should be fixed by the latest commit on 6/1/20, correct?

**Comment by mrp089** [comment]
Yes! I'm closing it
