### ISSUE TITLE
Boundary conditions mislabeled in solver.in file

### ISSUE THREAD

**Issue by schwarz-e** [SimVascular/svOneDSolver#77]
The solver.in file resistances are not applied to the same vessel as in the Inlet and Outlet BC GUI. This may happen if you change the name of your branches (maybe in the Modeling toolbar as well).

**Comment by schwarz-e** [comment]
Erica Leigh Schwarz has shared OneDrive for Business files with you. To view them, click the links below.
<https://office365stanford-my.sharepoint.com/personal/schwarze_stanford_edu/Documents/Attachments/Coronary%20Artery%20Disease%20copy.zip>
[https://r1.res.office365.com/owa/prem/images/dc-zip_20.png]<https://office365stanford-my.sharepoint.com/personal/schwarze_stanford_edu/Documents/Attachments/Coronary%20Artery%20Disease%20copy.zip>
Coronary Artery Disease copy.zip<https://office365stanford-my.sharepoint.com/personal/schwarze_stanford_edu/Documents/Attachments/Coronary%20Artery%20Disease%20copy.zip>

<https://office365stanford-my.sharepoint.com/personal/schwarze_stanford_edu/Documents/Attachments/MidtermProj_NEW.zip>
[https://r1.res.office365.com/owa/prem/images/dc-zip_20.png]<https://office365stanford-my.sharepoint.com/personal/schwarze_stanford_edu/Documents/Attachments/MidtermProj_NEW.zip>
MidtermProj_NEW.zip<https://office365stanford-my.sharepoint.com/personal/schwarze_stanford_edu/Documents/Attachments/MidtermProj_NEW.zip>

Yep, both attached. These are both from midterm projects for the class- but for both students their listed BCs in the GUI don't match the solver.in.

Erica Schwarz | she/her
Stanford University | Marsden Lab
520-870-3485 | ***@***.***
________________________________

**Comment by schwarz-e** [comment]
To view MidtermProj_NEW.zip, sign in<https://office365stanford-my.sharepoint.com/personal/schwarze_stanford_edu/_layouts/15/acceptinvite.aspx?invitation=%7B65FEDD3C%2D8A29%2D4E9B%2DA74F%2D0DEE4B71C059%7D&listId=230d4dde%2Dbcea%2D4175%2D8bcb%2D867ed097230e&itemId=022572b6%2Db0d3%2D45f9%2Dabd3%2Ddf0f66b70a94> or create an account.

**Comment by schwarz-e** [comment]
To view Coronary Artery Disease copy.zip, sign in<https://office365stanford-my.sharepoint.com/personal/schwarze_stanford_edu/_layouts/15/acceptinvite.aspx?invitation=%7B75A827AD%2DDD40%2D4329%2DAD35%2D3FE1F89211B1%7D&listId=230d4dde%2Dbcea%2D4175%2D8bcb%2D867ed097230e&itemId=d106e755%2Dd077%2D4623%2Da9ce%2Dd69283ba04ba> or create an account.

**Comment by mrp089** [comment]
Filed as bug in https://github.com/SimVascular/SimVascular/issues/848
